#define KSPEED_UP SDLK_UP
#define KSPEED_DOWN SDLK_DOWN
#define KGEAR_UP SDLK_PLUS
#define KGEAR_DOWN SDLK_MINUS
#define KJUMP SDLK_SPACE
#define KSTEER_LEFT SDLK_LEFT
#define KSTEER_RIGHT SDLK_RIGHT
